"""Per-field evidence sheet for the human 'why it matters' judgement (Problem 2).

For each field in catalogue / inventory / users, shows what the values actually look
like: cardinality, real examples, and the distribution detail that would change how you
judge the field's role in the shop or the chatbot.

    .venv/bin/python field_evidence.py   ->  output/field_evidence.md
"""
from __future__ import annotations
import json, sqlite3, statistics
from pathlib import Path

DB, OUT = Path("data/campus_customs.db"), Path("output/field_evidence.md")
SECRET = {"password_hash"}
L: list[str] = []


def w(s: str = "") -> None:
    L.append(s)


def examples(conn, table, col, n=4):
    """A few real values, longest-first so prose fields show their true shape."""
    rows = conn.execute(
        f"SELECT DISTINCT \"{col}\" FROM '{table}' WHERE \"{col}\" IS NOT NULL ORDER BY LENGTH(CAST(\"{col}\" AS TEXT)) DESC LIMIT ?",
        (n,),
    ).fetchall()
    return [r[0] for r in rows]


def field(conn, table, col, note=""):
    total = conn.execute(f"SELECT COUNT(*) FROM '{table}'").fetchone()[0]
    distinct = conn.execute(f"SELECT COUNT(DISTINCT \"{col}\") FROM '{table}'").fetchone()[0]
    nulls = conn.execute(f"SELECT COUNT(*) FROM '{table}' WHERE \"{col}\" IS NULL").fetchone()[0]

    w(f"\n#### `{col}`")
    w(f"\n{distinct} distinct / {total} rows · {nulls} null{'  ·  ' + note if note else ''}\n")

    if col in SECRET:
        w("Values redacted (password hashes). Format: `pbkdf2_sha256$<iterations>$<salt>$<hash>`.\n")
        return

    if distinct <= 8:  # small domain: show it all, it IS the evidence
        w("Complete value list:\n")
        for v, n in conn.execute(f"SELECT \"{col}\", COUNT(*) FROM '{table}' GROUP BY 1 ORDER BY 2 DESC"):
            w(f"- `{v}` — {n} rows")
        w("")
        return

    w("Examples:\n")
    for v in examples(conn, table, col):
        text = str(v)
        w(f"- {text if len(text) < 300 else text[:300] + '…'}")
    w("")


def main():
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    OUT.parent.mkdir(exist_ok=True)

    w("# Field evidence — for the human 'why it matters' judgement")
    w("\nGenerated by `field_evidence.py`. Shows what each field's values actually look like,")
    w("so the judgement in `harness.md` is made against the data rather than a description of it.")

    w("\n---\n\n## `catalogue` (102 rows, one per product)")
    for c, note in [
        ("product_id", "slug; also the image filename stem"),
        ("name", "title-cased from the slug"),
        ("garment_type", "22 values for ~7 real categories"),
        ("description", "one paragraph of prose per product"),
        ("colors", "JSON array"),
        ("search_tags", "JSON array, 4–12 per product"),
        ("image_file_path", "relative to data/"),
        ("price", "7 distinct values"),
    ]:
        field(conn, "catalogue", c, note)

    # Extra colour/tag detail: these drive chat matching, so show the vocabulary.
    cols, tags = {}, {}
    for cj, tj in conn.execute("SELECT colors, search_tags FROM catalogue"):
        for x in json.loads(cj):
            cols[x] = cols.get(x, 0) + 1
        for x in json.loads(tj):
            tags[x] = tags.get(x, 0) + 1
    w("\n**All 22 colors, by frequency:**\n")
    w(", ".join(f"`{k}` ({v})" for k, v in sorted(cols.items(), key=lambda kv: -kv[1])))
    w(f"\n**Most common of the {len(tags)} tags:**\n")
    w(", ".join(f"`{k}` ({v})" for k, v in sorted(tags.items(), key=lambda kv: -kv[1])[:25]))
    singles = sum(1 for v in tags.values() if v == 1)
    w(f"\n{singles} of {len(tags)} tags appear on exactly one product — a long tail of specific hooks.")

    w("\n---\n\n## `inventory` (612 rows, one per product × size)")
    for c, note in [("id", "surrogate key"), ("product_id", "FK → catalogue"),
                    ("size", "6 sizes, every product has all 6"), ("quantity", "the honesty field")]:
        field(conn, "inventory", c, note)

    q = [r[0] for r in conn.execute("SELECT quantity FROM inventory")]
    w(f"\n**Quantity distribution:** min {min(q)} · max {max(q)} · mean {statistics.mean(q):.1f} · "
      f"median {statistics.median(q)} · SD {statistics.stdev(q):.1f}")
    w(f"\n- Zero-stock rows: **{sum(1 for x in q if x == 0)} of {len(q)}** ({sum(1 for x in q if x==0)/len(q):.0%})")
    w("- Out-of-stock rows per size:\n")
    for s, n, z in conn.execute("SELECT size, COUNT(*), SUM(quantity=0) FROM inventory GROUP BY 1 ORDER BY 3 DESC"):
        w(f"  - `{s}` — {z} of {n} out ({z/n:.0%})")

    w("\n---\n\n## `users` (3 rows)")
    for c, note in [("id", "PK"), ("name", "legacy full name"), ("email", "login identifier, UNIQUE"),
                    ("password_hash", "never leaves the DB"), ("created_at", ""),
                    ("first_name", "what the bot greets you by"), ("last_name", "")]:
        field(conn, "users", c, note)

    w("\n**Note on `name` vs `first_name`/`last_name`:** both are populated and agree for all 3 rows,")
    w("so the full name is stored twice. One of them should be the single source of truth.\n")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
